name: Assignment CI

on:
workflow_dispatch:
push:
branches:
- main

jobs:
test:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v4

- name: 23f2003496@ds.study.iitm.ac.in - Print hello
run: echo "Hello from GitHub Actions!"
